name: Deploy to Go54

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install FTP deployment tool
      run: |
        sudo apt-get install -y lftp

    - name: Deploy files via FTP
      run: |
        lftp -f "
        open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}
        mirror --reverse --delete --verbose ./C:\Users\yeni\greenpath /public_html
        bye
        "
      env:
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
